//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codehub.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CodehubEntities : DbContext
    {
        public CodehubEntities()
            : base("name=CodehubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusinessDepartment> BusinessDepartments { get; set; }
        public virtual DbSet<BusinessEmployee> BusinessEmployees { get; set; }
        public virtual DbSet<BusinessRole> BusinessRoles { get; set; }
        public virtual DbSet<BusinessUser> BusinessUsers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
    }
}
